#show_version=6
# deff_097_zuse_all_targets_v00: ALL TARGETS value, clip anim_097_img5609.
# Same sounds and tube show as deff_097_zuse_all_targets; only the clip differs. random pick of 2 clips.
- time: 0ms
  slides:
    deff_097_zuse_all_targets_v00:
      action: play
  sounds:
    call_0af:
      action: play
- time: 979ms
  sounds:
    call_0b0:
      action: play
- time: 1793ms
  slides:
    deff_097_zuse_all_targets_v00:
      action: remove
