#show_version=6
# deff_068_quorra_jackpot: (DOUBLE) JACKPOT
# ROM trigger: Quorra Multiball jackpot. Timing from emulation.
- time: 0ms
  slides:
    deff_068_quorra_jackpot:
      action: play
  shows:
    leff_038:
      action: play
      loops: 0
  sounds:
    call_06c:
      action: play
- time: 1806ms
  sounds:
    call_06d:
      action: play
- time: 3844ms
  slides:
    deff_068_quorra_jackpot:
      action: remove
