#show_version=6
# deff_111_disc_multiball_progress_v02: n MORE TO START DISC MULTIBALL (random film clip), clip anim_060_img4182 + anim_061_img4230.
# Same sounds and tube show as deff_111_disc_multiball_progress; only the clip differs. random pick of 11 clips.
- time: 0ms
  slides:
    deff_111_disc_multiball_progress_v02:
      action: play
- time: 1ms
  shows:
    leff_062:
      action: play
- time: 4121ms
  slides:
    deff_111_disc_multiball_progress_v02:
      action: remove
