#show_version=6
# ROM lamp effect 145 (leff table 0x040e23e4, function 0x1027bf4, priority 209). Captured in emulation.
# Plays once. 
# Started by: effect 120 (deff_120_sea_stage_5)
- duration: 113ms
  flashers:
    f_video_game: 64ms
    f_zen_flasher: 64ms
- duration: 114ms
  flashers:
    f_bottom_arch_left: 64ms
    f_left_ramp: 64ms
- duration: 113ms
  flashers:
    f_bottom_arch_right: 64ms
    f_right_ramp: 64ms
- duration: 115ms
  flashers:
    f_disc_left: 64ms
    f_disc_right: 64ms
- duration: 113ms
  flashers:
    f_backpanel: 64ms
    f_recognizer: 64ms
- duration: 114ms
  flashers:
    f_blue_disc: 64ms
    f_red_disc: 64ms
- duration: 113ms
  flashers:
    f_video_game: 64ms
    f_zen_flasher: 64ms
- duration: 115ms
  flashers:
    f_bottom_arch_left: 64ms
    f_left_ramp: 64ms
- duration: 113ms
  flashers:
    f_bottom_arch_right: 64ms
    f_right_ramp: 64ms
- duration: 114ms
  flashers:
    f_disc_left: 64ms
    f_disc_right: 64ms
- duration: 113ms
  flashers:
    f_backpanel: 64ms
    f_recognizer: 64ms
- duration: 114ms
  flashers:
    f_blue_disc: 64ms
    f_red_disc: 64ms
- duration: 113ms
  flashers:
    f_video_game: 64ms
    f_zen_flasher: 64ms
- duration: 115ms
  flashers:
    f_bottom_arch_left: 64ms
    f_left_ramp: 64ms
- duration: 113ms
  flashers:
    f_bottom_arch_right: 64ms
    f_right_ramp: 64ms
- duration: 114ms
  flashers:
    f_disc_left: 64ms
    f_disc_right: 64ms
- duration: 113ms
  flashers:
    f_backpanel: 64ms
    f_recognizer: 64ms
- duration: 115ms
  flashers:
    f_blue_disc: 64ms
    f_red_disc: 64ms
- duration: 113ms
  flashers:
    f_video_game: 64ms
    f_zen_flasher: 64ms
- duration: 114ms
  flashers:
    f_bottom_arch_left: 64ms
    f_left_ramp: 64ms
- duration: 113ms
  flashers:
    f_bottom_arch_right: 64ms
    f_right_ramp: 64ms
- duration: 115ms
  flashers:
    f_disc_left: 64ms
    f_disc_right: 64ms
- duration: 112ms
  flashers:
    f_backpanel: 64ms
    f_recognizer: 64ms
- duration: 115ms
  flashers:
    f_blue_disc: 64ms
    f_red_disc: 64ms
- duration: 113ms
  flashers:
    f_video_game: 64ms
    f_zen_flasher: 64ms
- duration: 114ms
  flashers:
    f_bottom_arch_left: 64ms
    f_left_ramp: 64ms
- duration: 113ms
  flashers:
    f_bottom_arch_right: 64ms
    f_right_ramp: 64ms
- duration: 115ms
  flashers:
    f_disc_left: 64ms
    f_disc_right: 64ms
- duration: 113ms
  flashers:
    f_backpanel: 64ms
    f_recognizer: 64ms
- duration: 114ms
  flashers:
    f_blue_disc: 64ms
    f_red_disc: 64ms
- duration: 113ms
  flashers:
    f_video_game: 64ms
    f_zen_flasher: 64ms
- duration: 130ms
  flashers:
    f_bottom_arch_left: 64ms
    f_left_ramp: 64ms
