#show_version=6
# ROM lamp effect 165 (leff table 0x040e23e4, function 0x102fe34, priority 192). Captured in emulation.
# Plays once. 
# Started by: effect 140 (deff_140_portal_multiball_intro)
- duration: 14ms
  flashers:
    f_video_game: 48ms
- duration: 84ms
  lights:
    l_advance_quorra: '000000'
    l_bottom_bumper: '000000'
    l_bumpers: '000000'
    l_center_clu: '000000'
    l_center_disc: '000000'
    l_center_flynn: '000000'
    l_center_gem: '000000'
    l_center_light_cycle: '000000'
    l_center_portal: '000000'
    l_center_quorra: '000000'
    l_center_recognizer: '000000'
    l_center_tron: '000000'
    l_center_zuse: '000000'
    l_clu_c: '000000'
    l_clu_l: '000000'
    l_clu_u: '000000'
    l_double_scoring: '000000'
    l_eject_clu: '000000'
    l_eject_light_cycle: '000000'
    l_eject_portal: '000000'
    l_eject_quorra: '000000'
    l_flynns_arcade: '000000'
    l_l_inner_loop_arrow: '000000'
    l_l_inner_loop_clu: '000000'
    l_l_inner_loop_disc: '000000'
    l_l_inner_loop_light_cycle: '000000'
    l_l_loop_arrow: '000000'
    l_left_bumper: '000000'
    l_left_orbit_clu: ffffff
    l_left_orbit_disc: '000000'
    l_left_orbit_light_cycle: '000000'
    l_left_ramp_arrow: '000000'
    l_left_ramp_disc: '000000'
    l_left_ramp_light_cycle: '000000'
    l_r_inner_loop_arrow: '000000'
    l_r_inner_loop_disc: '000000'
    l_r_inner_loop_light_cycle: '000000'
    l_r_loop_arrow: '000000'
    l_r_ramp_arrow: '000000'
    l_r_ramp_light_cycle: '000000'
    l_recognizer_3_bank: '000000'
    l_recognizer_pos_1: '000000'
    l_recognizer_pos_2: '000000'
    l_recognizer_pos_3: '000000'
    l_right_bumper: '000000'
    l_right_orbit_clu: '000000'
    l_right_orbit_disc: '000000'
    l_right_orbit_light_cycle: '000000'
    l_right_ramp_disc: '000000'
    l_spinners: '000000'
    l_tron_n: '000000'
    l_tron_o: '000000'
    l_tron_r: '000000'
    l_tron_t: '000000'
    l_zuse_e: '000000'
    l_zuse_s: '000000'
    l_zuse_u: '000000'
    l_zuse_z: '000000'
- duration: 13ms
  flashers:
    f_video_game: 48ms
- duration: 83ms
  lights:
    l_left_orbit_light_cycle: ffffff
- duration: 15ms
  flashers:
    f_video_game: 48ms
- duration: 83ms
  lights:
    l_left_orbit_disc: ffffff
- duration: 14ms
  flashers:
    f_video_game: 48ms
- duration: 83ms
  lights:
    l_l_loop_arrow: ffffff
- duration: 14ms
  flashers:
    f_video_game: 48ms
- duration: 84ms
  lights:
    l_left_ramp_light_cycle: ffffff
- duration: 14ms
  flashers:
    f_video_game: 48ms
- duration: 83ms
  lights:
    l_left_ramp_disc: ffffff
- duration: 14ms
  flashers:
    f_video_game: 48ms
- duration: 83ms
  lights:
    l_left_ramp_arrow: ffffff
- duration: 15ms
  flashers:
    f_video_game: 48ms
- duration: 84ms
  lights:
    l_advance_quorra: ffffff
- duration: 13ms
  flashers:
    f_video_game: 48ms
- duration: 83ms
  lights:
    l_l_inner_loop_clu: ffffff
- duration: 15ms
  flashers:
    f_video_game: 48ms
- duration: 84ms
  lights:
    l_l_inner_loop_light_cycle: ffffff
- duration: 13ms
  flashers:
    f_video_game: 48ms
- duration: 83ms
  lights:
    l_l_inner_loop_disc: ffffff
- duration: 15ms
  flashers:
    f_video_game: 48ms
- duration: 84ms
  lights:
    l_l_inner_loop_arrow: ffffff
- duration: 13ms
  flashers:
    f_video_game: 48ms
- duration: 83ms
  lights:
    l_r_inner_loop_light_cycle: ffffff
- duration: 15ms
  flashers:
    f_video_game: 48ms
- duration: 83ms
  lights:
    l_r_inner_loop_disc: ffffff
- duration: 14ms
  flashers:
    f_video_game: 48ms
- duration: 84ms
  lights:
    l_r_inner_loop_arrow: ffffff
- duration: 14ms
  flashers:
    f_video_game: 48ms
- duration: 83ms
  lights:
    l_r_ramp_light_cycle: ffffff
- duration: 14ms
  flashers:
    f_video_game: 48ms
- duration: 84ms
  lights:
    l_right_ramp_disc: ffffff
- duration: 14ms
  flashers:
    f_video_game: 48ms
- duration: 83ms
  lights:
    l_r_ramp_arrow: ffffff
- duration: 14ms
  flashers:
    f_video_game: 48ms
- duration: 84ms
  lights:
    l_right_orbit_clu: ffffff
- duration: 14ms
  flashers:
    f_video_game: 48ms
- duration: 83ms
  lights:
    l_right_orbit_light_cycle: ffffff
- duration: 14ms
  flashers:
    f_video_game: 48ms
- duration: 83ms
  lights:
    l_right_orbit_disc: ffffff
- duration: 15ms
  flashers:
    f_video_game: 48ms
- duration: 84ms
  lights:
    l_r_loop_arrow: ffffff
- duration: 113ms
  flashers:
    f_video_game: 64ms
    f_zen_flasher: 64ms
- duration: 114ms
  flashers:
    f_bottom_arch_left: 64ms
    f_left_ramp: 64ms
- duration: 113ms
  flashers:
    f_bottom_arch_right: 64ms
    f_right_ramp: 64ms
- duration: 114ms
  flashers:
    f_disc_left: 64ms
    f_disc_right: 64ms
- duration: 1ms
  flashers:
    f_backpanel: 64ms
- duration: 112ms
  flashers:
    f_recognizer: 64ms
- duration: 115ms
  flashers:
    f_blue_disc: 64ms
    f_red_disc: 64ms
- duration: 113ms
  flashers:
    f_video_game: 64ms
    f_zen_flasher: 64ms
- duration: 114ms
  flashers:
    f_bottom_arch_left: 64ms
    f_left_ramp: 64ms
- duration: 113ms
  flashers:
    f_bottom_arch_right: 64ms
    f_right_ramp: 64ms
- duration: 115ms
  flashers:
    f_disc_left: 64ms
    f_disc_right: 64ms
- duration: 113ms
  flashers:
    f_backpanel: 64ms
    f_recognizer: 64ms
- duration: 114ms
  flashers:
    f_blue_disc: 64ms
    f_red_disc: 64ms
- duration: 113ms
  flashers:
    f_video_game: 64ms
    f_zen_flasher: 64ms
- duration: 114ms
  flashers:
    f_bottom_arch_left: 64ms
    f_left_ramp: 64ms
- duration: 113ms
  flashers:
    f_bottom_arch_right: 64ms
    f_right_ramp: 64ms
- duration: 115ms
  flashers:
    f_disc_left: 64ms
    f_disc_right: 64ms
- duration: 113ms
  flashers:
    f_backpanel: 64ms
    f_recognizer: 64ms
- duration: 114ms
  flashers:
    f_blue_disc: 64ms
    f_red_disc: 64ms
- duration: 113ms
  flashers:
    f_video_game: 64ms
    f_zen_flasher: 64ms
- duration: 114ms
  flashers:
    f_bottom_arch_left: 64ms
    f_left_ramp: 64ms
- duration: 1ms
  flashers:
    f_bottom_arch_right: 64ms
- duration: 113ms
  flashers:
    f_right_ramp: 64ms
- duration: 114ms
  flashers:
    f_disc_left: 64ms
    f_disc_right: 64ms
- duration: 113ms
  flashers:
    f_backpanel: 64ms
    f_recognizer: 64ms
- duration: 115ms
  flashers:
    f_blue_disc: 64ms
    f_red_disc: 64ms
- duration: 112ms
  flashers:
    f_video_game: 64ms
    f_zen_flasher: 64ms
- duration: 115ms
  flashers:
    f_bottom_arch_left: 64ms
    f_left_ramp: 64ms
- duration: 113ms
  flashers:
    f_bottom_arch_right: 64ms
    f_right_ramp: 64ms
- duration: 114ms
  flashers:
    f_disc_left: 64ms
    f_disc_right: 64ms
- duration: 113ms
  flashers:
    f_backpanel: 64ms
    f_recognizer: 64ms
- duration: 115ms
  flashers:
    f_blue_disc: 64ms
    f_red_disc: 64ms
- duration: 113ms
  flashers:
    f_video_game: 64ms
    f_zen_flasher: 64ms
- duration: 130ms
  flashers:
    f_bottom_arch_left: 64ms
    f_left_ramp: 64ms
