#show_version=6
# Library animation 47: images 3711-3770, 60 frames at 33 ms (ROM timing).
- time: 0ms
  slides:
    lib_anim_047_img3711:
      action: play
- time: 1960ms
  slides:
    lib_anim_047_img3711:
      action: remove
