#show_version=6
# Library animation 85: images 4981-5009, 29 frames at 65 ms (ROM timing).
- time: 0ms
  slides:
    lib_anim_085_img4981:
      action: play
- time: 1894ms
  slides:
    lib_anim_085_img4981:
      action: remove
