#show_version=6
# Library animation 66: images 4361-4389, 29 frames at 49 ms (ROM timing).
- time: 0ms
  slides:
    lib_anim_066_img4361:
      action: play
- time: 1421ms
  slides:
    lib_anim_066_img4361:
      action: remove
