#show_version=6
# Library animation 140: images 7911-7976, 66 frames at 49 ms (default timing, not found in code).
- time: 0ms
  slides:
    lib_anim_140_img7911:
      action: play
- time: 3233ms
  slides:
    lib_anim_140_img7911:
      action: remove
