#show_version=6
# Library animation 108: images 6229-6350, 122 frames at 49 ms (default timing, not found in code).
- time: 0ms
  slides:
    lib_anim_108_img6229:
      action: play
- time: 5977ms
  slides:
    lib_anim_108_img6229:
      action: remove
