#show_version=6
# Library animation 26: images 3008-3088, 81 frames at 49 ms (ROM timing).
- time: 0ms
  slides:
    lib_anim_026_img3008:
      action: play
- time: 3968ms
  slides:
    lib_anim_026_img3008:
      action: remove
