#show_version=6
# Library animation 125: images 7159-7194, 36 frames at 49 ms (default timing, not found in code).
- time: 0ms
  slides:
    lib_anim_125_img7159:
      action: play
- time: 1764ms
  slides:
    lib_anim_125_img7159:
      action: remove
