#show_version=6
# Library animation 68: images 4430-4465, 36 frames at 49 ms (ROM timing).
- time: 0ms
  slides:
    lib_anim_068_img4430:
      action: play
- time: 1764ms
  slides:
    lib_anim_068_img4430:
      action: remove
