#show_version=6
# Library animation 27: images 3089-3109, 21 frames at 49 ms (ROM timing).
- time: 0ms
  slides:
    lib_anim_027_img3089:
      action: play
- time: 1029ms
  slides:
    lib_anim_027_img3089:
      action: remove
