#show_version=6
# Library animation 121: images 6897-7008, 112 frames at 49 ms (default timing, not found in code).
- time: 0ms
  slides:
    lib_anim_121_img6897:
      action: play
- time: 5487ms
  slides:
    lib_anim_121_img6897:
      action: remove
