#show_version=6
# Library animation 134: images 7670-7708, 39 frames at 49 ms (default timing, not found in code).
- time: 0ms
  slides:
    lib_anim_134_img7670:
      action: play
- time: 1911ms
  slides:
    lib_anim_134_img7670:
      action: remove
