#show_version=6
# Library animation 98: images 5626-5669, 44 frames at 49 ms (ROM timing).
- time: 0ms
  slides:
    lib_anim_098_img5626:
      action: play
- time: 2156ms
  slides:
    lib_anim_098_img5626:
      action: remove
