#show_version=6
# Library animation 96: images 5569-5608, 40 frames at 65 ms (ROM timing).
- time: 0ms
  slides:
    lib_anim_096_img5569:
      action: play
- time: 2613ms
  slides:
    lib_anim_096_img5569:
      action: remove
