#show_version=6
# Library animation 30: images 3161-3204, 44 frames at 49 ms (ROM timing).
- time: 0ms
  slides:
    lib_anim_030_img3161:
      action: play
- time: 2156ms
  slides:
    lib_anim_030_img3161:
      action: remove
