# deff id: (slug, what it shows, mode / trigger)  -- written from on-screen text, emulator capture and code location
L={
1:("attract_score_display","Attract mode: game over, credits, high scores (background effect)","attract mode"),
2:("volume","VOLUME n","volume buttons (service)"),
3:("technician_alert","Technician alert / service menu prompt","service"),
4:("coil_power_disabled","50V / 20V DISABLED","service: coil power off (coin door open)"),
5:("boot_version","Boot screen: TRON L.E. / U.S.A. / V1.74 / ENGLISH","power on"),
6:("frequency_test","Line frequency readout","service/diagnostic"),
7:("wrong_country","THIS MACHINE WILL NOT OPERATE IN THIS COUNTRY","boot check"),
8:("hw_sw_mismatch","HARDWARE/SOFTWARE MISMATCH","boot check"),
9:("number_entry","n/10 - 10 counter display","OS utility (unknown use)"),
10:('coin_credit', 'Credits screen (same display as effects 15 and 17)', 'coin inserted'),
11:("locating_pinballs","LOCATING PINBALLS / PLEASE WAIT","ball search"),
12:("message","Generic text message (%s)","OS message"),
13:("pinball_missing","PINBALL MISSING / PLEASE WAIT","ball missing at game start"),
14:("score_refresh","Score display refresh","score change"),
15:('start_button', 'Credits screen (same display as effects 10 and 17)', 'start button without enough credits'),
16:("tournament_game","TOURNAMENT GAME / credits","tournament start button"),
17:('service_credits', 'Credits screen (same display as effects 10 and 15)', 'service credit button'),
18:("bump_n_win","BUMP 'N' WIN score","Bump'n'Win feature (operator option)"),
19:("score_display","Main in-game score display: BALL n / score (background effect)","in game, default display"),
20:("ball_saved","BALL SAVED / KEEP SHOOTING","ball save (outlane drain during ball save)"),
21:("tilt","TILT (background effect)","tilt"),
22:('unused', '(empty: the function only returns)', 'none: unused in v1.74 (effect function is a bare return; the tilt warning on screen is effect 23)'),
23:("danger","DANGER","tilt warning"),
24:("slam_tilt","SLAM TILT","slam tilt"),
25:("bonus","TOTAL BONUS","end of ball bonus"),
26:("shoot_again","PLAYER n SHOOT AGAIN","extra ball / shoot again"),
27:("instant_info","INSTANT INFO","instant info (flipper buttons held; not captured, flipper buttons were not driven)"),
28:("replay","REPLAY","replay score reached"),
29:("bump_n_win_award","BUMP 'N' WIN award","Bump'n'Win"),
30:("tickets","n TICKET(S)","ticket dispenser award"),
31:("enter_initials","PLAYER n ENTER INITIALS","high score entry"),
32:("high_score_value","High score value","high score entry"),
33:("high_score_player","PLAYER n (high score)","high score awarded"),
34:("tournament_not_qualified","SORRY, YOU DID NOT QUALIFY","tournament end"),
35:("tournament_qualified","PLAYER n YOU QUALIFIED!","tournament end"),
36:("tournament_place","nTH PLACE","tournament end"),
37:("tournament_rank","PLAYER n YOU ARE IN nTH PLACE!","tournament end"),
38:("match","MATCH sequence","end of game match"),
39:("competition_ready","COMPETITION MODE READY / PRESS START NOW","competition mode"),
40:("player_up","PLAYER n (you're up)","start of each player's ball"),
41:("left_spinner_value","LEFT SPINNER = value","left spinner (sw44)"),
42:("right_spinner_value","RIGHT SPINNER = value","right orbit spinner (sw36)"),
43:("pop_bumpers","n MORE POP BUMPERS = value","pop bumpers (sw30-32)"),
44:("bumper_level_complete","LEVEL n COMPLETED","pop bumper level completed (sw30-32)"),
45:('light_cycle_maze', 'LIGHT CYCLE MAZE video mode', "Light Cycle Maze video mode. Its start path (FUN_0102e584) has no caller in v1.74, so the trigger is unknown and it is possibly unused (not verified). Not linked to Flynn's Arcade"),
46:("disc_multiball_intro","DISC MULTIBALL intro animation","Disc Multiball start"),
47:("disc_multiball_running","DISC MULTIBALL status: shoot recognizer / spinning disc (background)","during Disc Multiball"),
48:("disc_multiball_jackpot","DISC MULTIBALL JACKPOT","Disc Multiball jackpot (disc opto sw41, right inner loop sw39, recognizer bank)"),
49:("disc_multiball_jackpot_2","DISC MULTIBALL JACKPOT (variant)","Disc Multiball jackpot"),
50:("disc_multiball_super_jackpot","SUPER JACKPOT","Disc Multiball super jackpot"),
51:("disc_multiball_total","Disc Multiball TOTAL","Disc Multiball end"),
52:("disc_multiball_restart","DISC MULTIBALL RESTART","Disc Multiball restart offer"),
53:("disc_multiball_restart_running","DISC MULTIBALL RESTART / SHOOT DISC n (background)","during multiball restart"),
54:("disc_multiball_restarted","DISC MULTIBALL (restarted)","Disc Multiball restart made"),
55:("multiball_lit","MULTIBALL IS LIT / n MORE TO LIGHT / EXTRA BALL","ramp exits (sw34/sw37) progress toward End of Line multiball"),
56:("end_of_line_intro","END OF LINE MULTIBALL intro","End of Line (Daft Punk) Multiball start"),
57:("end_of_line_running","SWITCHES = value (background)","during End of Line Multiball"),
58:("end_of_line_jackpot","JACKPOT","End of Line Multiball jackpot"),
59:("end_of_line_double_jackpot","DOUBLE JACKPOT","End of Line Multiball double jackpot"),
60:("end_of_line_add_ball","BALL ADDED / n MORE FOR ADD-A-BALL","End of Line Multiball add-a-ball (disc, ramps)"),
61:("end_of_line_total","END OF LINE MULTIBALL TOTAL","End of Line Multiball end"),
62:("quorra_progress","n TO LIGHT QUORRA MULTIBALL","Quorra advance (left spinner sw44 area)"),
63:("quorra_lit","QUORRA MULTIBALL IS LIT","Quorra Multiball lit"),
64:("quorra_multiball_intro","QUORRA MULTIBALL intro","Quorra Multiball start"),
65:("quorra_multiball_running","QUORRA MULTIBALL status (background)","during Quorra Multiball"),
66:("quorra_add_ball_progress","QUORRA MULTIBALL n MORE TO ADD BALL","Quorra Multiball shots"),
67:("quorra_ball_added","QUORRA MULTIBALL BALL ADDED","Quorra Multiball add-a-ball"),
68:("quorra_jackpot","(DOUBLE) JACKPOT","Quorra Multiball jackpot"),
69:("quorra_super_jackpot","(DOUBLE) SUPER JACKPOT","Quorra Multiball super jackpot"),
70:("quorra_total","QUORRA MULTIBALL TOTAL","Quorra Multiball end"),
71:("clu_intro","TERMINATE CLU / SHOOT CLU HELMET SHOTS","CLU hurry-up start"),
72:("clu_running","TERMINATE CLU timer (background)","during CLU hurry-up"),
73:("clu_award","CLU hurry-up award value","CLU hurry-up shot made"),
74:("clu_total","TERMINATE CLU TOTAL","CLU hurry-up end"),
75:("gem_progress","n MORE TO START FOLLOW GEM","right inner loop (sw39)"),
76:("gem_intro","Follow Gem intro (hand, SHOOT RIGHT INNER LOOP)","Follow Gem hurry-up start"),
77:("gem_running","FOLLOW GEM timer (background)","during Follow Gem"),
78:("gem_award","FOLLOW GEM n FOLLOWINGS","Follow Gem shot made (right inner loop sw39)"),
79:("gem_total","FOLLOW GEM TOTAL","Follow Gem end"),
80:("hurryup_progress","n MORE TO LIGHT HURRY-UP / HURRY-UP IS LIT","CLU targets (sw14, sw25, sw28)"),
81:("special_lit","SPECIAL IS LIT","special lit"),
82:("special","SPECIAL","special collected at outlane (sw24/sw29)"),
83:("light_cycle_progress","n MORE LIGHT CYCLE","right inner loop / orbit / ramp shots toward Light Cycle"),
84:("light_cycle_lit","LIGHT CYCLE IS LIT","Light Cycle Multiball lit"),
85:("light_cycle_intro","LIGHT CYCLE intro","Light Cycle Multiball start (captured in emulated play)"),
86:("light_cycle_running","LIGHT CYCLE MULTIBALL status (background)","during Light Cycle Multiball"),
87:("light_cycle_jackpot","JACKPOT","Light Cycle Multiball jackpot"),
88:("light_cycle_super_jackpot","SUPER JACKPOT","Light Cycle Multiball super jackpot"),
89:("light_cycle_double_super_jackpot","DOUBLE SUPER JACKPOT","Light Cycle Multiball"),
90:("light_cycle_total","LIGHT CYCLE MULTIBALL TOTAL","Light Cycle Multiball end"),
91:("zuse_collect","COLLECT FOR FASTSCORING / SOS ITEM","ZUSE targets (sw7, sw8, sw13, sw48)"),
92:("zuse_progress","n MORE FOR FASTSCORING","ZUSE targets"),
93:("zuse_ready","ZUSE FAST SCORING READY","ZUSE Fast Scoring lit"),
94:("zuse_intro","FAST SCORING: ALL TARGETS SCORE n POINTS","ZUSE Fast Scoring start"),
95:("zuse_running","ALL TARGETS = value (background)","during ZUSE Fast Scoring"),
96:("zuse_target_hit","Fast scoring target hit value","any target during Fast Scoring"),
97:("zuse_all_targets","ALL TARGETS value","Fast Scoring"),
98:("zuse_time_extended","TIME EXTENDED","Fast Scoring time extended"),
99:("zuse_total","FAST SCORING TOTAL","Fast Scoring end (captured in emulated play)"),
100:("zen","ZEN","ZEN rollover (sw12)"),
101:("skill_shot_left_ramp","SKILL SHOT (left ramp)","skill shot via left ramp exit sw37"),
102:("skill_shot_right_ramp","SKILL SHOT (right ramp)","skill shot via right ramp exit sw34"),
103:("skill_shot","SKILL SHOT (other)","skill shot"),
104:('arcade_lit', "FLYNN'S ARCADE IS LIT", "Flynn's Arcade becomes lit: the per-player arcade flag changes from off to on (code: FUN_0100ddb0, right orbit sw46 handler). Seen at game start because the arcade starts lit"),
105:('flynns_arcade_award', "Flynn's Arcade mystery award: 3 cabinets scroll in, the picked award blinks", "ball enters the VUK (sw11 VIDEO GAME EJECT) while Flynn's Arcade is lit; the game picks 1 of 12 awards (500K, advance Gem/CLU/ZUSE/Quorra/Disc/Light Cycle/Recognizer/Sea of Simulation, more time, light extra ball, light special) by weighted random"),
106:("tron_completed","n TRON COMPLETED","TRON targets complete (sw1-4)"),
107:("timed_award","COLLECT FOR TIMED AWARD","TRON / right ramp area"),
108:("disc_access_progress","n MORE TO ACCESS DISC","Recognizer 3-bank (sw49-51)"),
109:("disc_battle_ready","DISC BATTLE READY","Recognizer battle lit"),
110:("recognizer_battle_running","RECOGNIZER BATTLE! SHOOT RECOGNIZER (background)","during Recognizer battle"),
111:('disc_multiball_progress', 'n MORE TO START DISC MULTIBALL (random film clip)', 'disc opto (sw41) shots toward Disc Multiball (captured in emulated play)'),
112:("super_feature","SUPER POPS / SUPER SPINNERS / DOUBLE SCORING","Sea of Simulation award (captured in emulated play)"),
113:("sea_of_simulation_intro","SEA OF SIMULATION: COMPLETE ALL STAGES TO REACH THE PORTAL","Sea of Simulation start"),
114:("sea_of_simulation_running","SEA OF SIMULATION (background)","during Sea of Simulation"),
115:("sea_of_simulation_value","Sea of Simulation value","Sea of Simulation (captured in emulated play)"),
116:("sea_stage_1","Sea of Simulation stage animation 1","Sea of Simulation stage award"),
117:("sea_stage_2","Sea of Simulation stage animation 2","Sea of Simulation stage award"),
118:("sea_stage_3","Sea of Simulation stage animation 3","Sea of Simulation stage award"),
119:("sea_stage_4","Sea of Simulation stage animation 4","Sea of Simulation stage award"),
120:("sea_stage_5","Sea of Simulation stage animation 5","Sea of Simulation stage award"),
121:("sea_stage_6","Sea of Simulation stage animation 6","Sea of Simulation stage award"),
122:("sea_stage_7","Sea of Simulation stage animation 7","Sea of Simulation stage award"),
123:("sea_stage_8","Sea of Simulation stage animation 8","Sea of Simulation stage award"),
124:("sea_stage_9","Sea of Simulation stage animation 9","Sea of Simulation stage award"),
125:("sea_of_simulation_completed","SEA OF SIMULATION COMPLETED","all stages done"),
126:("sea_of_simulation_total","SEA OF SIMULATION TOTAL","Sea of Simulation end"),
127:('debug_image_viewer', 'Debug image-sequence viewer (frame number only)', 'none in game code (debug)'),
128:('clip_player_a', 'Clip player: plays film clip 0-29 by number', 'none in game code (no deff_start(0x80) call site; debug clip viewer, inferred)'),
129:('clip_player_b', 'Clip player: plays film clip 30-73 by number', 'none in game code (no deff_start(0x81) call site; debug clip viewer, inferred)'),
130:("game_over_disc_progress","GAME OVER / n MORE TO ACCESS DISC","end of game hint"),
131:("clu_face","CLU face animation","CLU feature"),
132:("extra_ball_lit","EXTRA BALL IS LIT","extra ball lit"),
133:("extra_ball","EXTRA BALL","extra ball collected"),
134:('left_ramp_big_bumps', 'LEFT RAMP MADE / SHOOT LEFT ORBIT FOR BIG BUMPS', 'left ramp made: Big Bumps (pop bumper feature) offered at the left orbit'),
135:("big_bumps","n BIG BUMPS","pop bumpers big bumps (sw30-32)"),
136:("find_flynn_intro","SHOOT ROVING RED ARROW TO FIND FLYNN","Find Flynn start (ZEN rollover sw12)"),
137:("flynn_found","FLYNN FOUND","Find Flynn completed"),
138:("combo","n WAY COMBO / JACKPOT","combo award"),
139:("end_of_line_jackpot_combo","END OF LINE JACKPOT","combo / End of Line jackpot"),
140:("portal_multiball_intro","PORTAL MULTIBALL intro (Sea of Simulation bonus)","Portal Multiball start"),
141:("portal_multiball_running","PORTAL MULTIBALL status (background)","during Portal Multiball"),
142:("portal_shot","Portal shot value","Portal Multiball shot (disc, inner loop, orbit)"),
143:("portal_super_jackpot","SUPER JACKPOT","Portal Multiball super jackpot"),
144:("portal_jackpot","Portal jackpot value","Portal Multiball jackpot"),
145:("portal_total","PORTAL MULTIBALL TOTAL","Portal Multiball end"),
}
